steps:
#
#  - label: rubocop
#    command: rubocop
#
#  - label: rspec
#    command: rspec
#
#  - wait
#
#  - block: Show sample
#
#  - wait
#
  # Run all your tests, uploading results as artifacts
  - label: Upload artifacts
    command: buildkite-agent artifact upload spec/sample_artifacts/**/*

  # Wait for the tests to finish
  - wait: ~
    continue_on_failure: true

  # Add test summary
  - label: annotate
    plugins:
      bugcrowd/test-summary#@VERSION@:
        inputs:
          - label: rspec
            artifact_path: spec/sample_artifacts/rspec*
            type: junit
            encoding: UTF-8
          - label: tap
            artifact_path: spec/sample_artifacts/example.tap
            type: tap
          - label: eslint
            artifact_path: spec/sample_artifacts/eslint.txt
            type: oneline
            # ignore the last two lines
            crop:
              start: 0
              end: 2
          - label: rubocop
            artifact_path: spec/sample_artifacts/rubocop.txt
            type: oneline
#          - label: stylelint
#            artifact_path: spec/sample_artifacts/stylelint.xml
#            type: junit
        # oneline or verbose annotation
        formatter:
          type: oneline
          hide_after: 20
        context: simple-annotation

  # Add test summary, including failure details
  - label: annotate
    plugins:
      bugcrowd/test-summary#@VERSION@:
        inputs:
          - label: rspec
            artifact_path: spec/sample_artifacts/rspec*
            type: junit
            encoding: UTF-8
          - label: tap
            artifact_path: spec/sample_artifacts/example.tap
            type: tap
          - label: eslint
            artifact_path: spec/sample_artifacts/eslint.txt
            type: oneline
            # ignore the last two lines
            crop:
              start: 0
              end: 2
          - label: rubocop
            artifact_path: spec/sample_artifacts/rubocop.txt
            type: oneline
#          - label: stylelint
#            artifact_path: spec/sample_artifacts/stylelint.xml
#            type: junit
        # oneline or verbose annotation
        formatter:
          type: verbose
          hide_after: 20
        context: verbose-annotation
